# ======================================================
# Microservicio JPA + MongoDB - WorkInX (Reto SENA Avanzado)
# ======================================================

server.port=8081

# 1. Base de Datos Relacional: MySQL (Spring Data JPA)
spring.datasource.url=jdbc:mysql://localhost:3306/workinx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración Hibernate JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 2. Base de Datos NoSQL: MongoDB (PLUS RETO)
spring.data.mongodb.uri=mongodb://localhost:27017/workinx_audit
spring.data.mongodb.auto-index-creation=true

# 3. Milla Extra: Límite de Peticiones por Minuto (Rate Limiting)
app.rate-limit.max-requests-per-minute=60

# 4. Logs del Sistema (RETO 3: INFO, WARN, ERROR)
logging.level.root=INFO
logging.level.com.workinx.microservicio=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
